### ISSUE TITLE
Configuration example

### ISSUE THREAD

**Issue by Katehuuh** [tumurzakov/AnimateDiff#1]
I created [tuneavideo.yaml](https://github.com/Katehuuh/AnimateDiff/blob/main/configs/prompts/tuneavideo.yaml) to be able to train `python train.py --config configs/prompts/tuneavideo.yaml` but i encountered an error: 
> TypeError: AnimationPipeline.__call__() missing 1 required positional argument: 'video_length'

or

> TypeError: TuneAVideoDataset.__init__() got an unexpected keyword argument 'video_length'

To fix i [modify dataset.py, train.py](https://github.com/Katehuuh/AnimateDiff/commit/93eff69e898d595081dff3bf77ad1598eeba448e) to get frames from video and remove from this part from my config:
```
train_data:
  video_length: 87
```

Training work but I can't confirm if the config is correct.

**Comment by tumurzakov** [comment]
https://github.com/tumurzakov/AnimateDiff/blob/main/Fine_tune_AnimateDiff.ipynb
